### PR TITLE
Add Thorntail support

### PR DESCRIPTION
**Pull request by juangon**
Just made some minor improvements on other things, among them, rename ModelReader so it isn't confiused with the eclipse package.

### CODE REVIEW

**Comment by juangon** [comment]
@arjantijms can you review? Thanks!

**Comment by juangon** [comment]
Bump

**Comment by arjantijms** [comment]
@juangon Thanks for the bump, was snowed under in tons of other Github notifications, twice :o

**Review by arjantijms — APPROVED** [review]

**Comment by juangon** [comment]
No problem at all. Thanks for reviewing and merging @arjantijms!

**Pull request merged**
